site_name: Studygood Shopware 6 App Dokumentation
edit_uri: blob/master/docs-source/
theme:
    name: 'material'
docs_dir: docs-source
site_dir: docs-html
extra_css:
    - 'jquery.fancybox.min.css'
    - 'extra.css'
extra_javascript:
    - 'jquery-3.5.0.slim.min.js'
    - 'jquery.fancybox.min.js'
    - 'extra.js'

nav:
    - Start: 'index.md'
    - Häufig gestellte Fragen (FAQ): 'faq/index.md'
    - Schnelleinrichtung:
        - Installation: 'installation/index.md'
        - Demo Daten anlegen: 'demo-assistant/index.md'
    - Kurs Konfiguration:
        - Kursverwaltung: 'course/index.md'
        - Kapitel: 'chapter/index.md'
        - Lektionen: 'lesson/index.md'
        - Prüfungen: 'test/index.md'
        - Board: 'board/index.md'
    - Theme Konfiguration: 'theme/index.md'
    - Shopware Store: 'https://store.shopware.com/appflix.html'
    - Kontakt: 'mailto:info@app-flix.de'
    - Impressum: 'imprint/index.md'
